# docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./college-event-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./college-event-backend
      dockerfile: Dockerfile
    ports:
      - "5081:5081"  
      - "5080:5080"
    volumes:
      - ./college-event-backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
